# Generated by Django 5.1.6 on 2025-02-23 19:09

import convertor.validatiors
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertor', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vtt',
            name='audio',
            field=models.FileField(help_text='Enter the path to the audio file.', upload_to='audio/%Y/%m/%d', validators=[convertor.validatiors.validate_audio_file]),
        ),
    ]
