# Generated by Django 5.1.6 on 2025-03-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convertor", "0002_alter_vtt_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vtt",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="vtt",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
