# Generated by Django 5.1.6 on 2025-03-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convertor", "0003_alter_vtt_options_alter_vtt_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vtt",
            name="title",
            field=models.CharField(default="Untitled Transcript", max_length=255),
        ),
    ]
