# Generated by Django 5.1.6 on 2025-03-15 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
